### ISSUE TITLE
Incomplete JUnit 5.9 support in Tycho 3.0.x

### ISSUE THREAD

**Issue by glatuske** [eclipse-tycho/tycho#1943] opened 2023-01-09 11:11 UTC
The JUnit 5.9 support in Tycho 3.0.1 is incomplete. Both providers (with and without vintage) include the 5.8 fragment instead of the newly added 5.9.

https://github.com/eclipse-tycho/tycho/blob/tycho-3.0.x/tycho-surefire/tycho-surefire-plugin/src/main/java/org/eclipse/tycho/surefire/provider/impl/JUnit59Provider.java#L52

https://github.com/eclipse-tycho/tycho/blob/tycho-3.0.x/tycho-surefire/tycho-surefire-plugin/src/main/java/org/eclipse/tycho/surefire/provider/impl/JUnit59WithVintageProvider.java#L52

This change has completed the JUnit 5.9 support but was not merged to tycho-3.0.x branch.

https://github.com/eclipse-tycho/tycho/commit/91cc9c7e9531da9ca3100dfb60d7ec7cc203bb3a#diff-fdbe3fce080e0fd768e8960e0a60436014c3e0419941f9db2b9921f8067bf9f5

**Comment by laeubi** [comment] 2023-01-09 11:15
@glatuske do you plan to [backport the change](https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md#backporting) including an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue?

**Comment by glatuske** [comment] 2023-01-09 11:22
@laeubi I can give it a try. But would you recommend to just backport the linked change from @mickaelistria and adding an integration test?

**Comment by laeubi** [comment] 2023-01-09 11:25
It depends a bit, there is no one-fits-all for backporting. It might be possible to just cherry-pick the change to the 3.x branch but it is also possible that you need to adjust it accordingly, in all cases a testcase ensures that the issue is demonstrated and fixed with the backporting change if it is not a trivial one.

**Comment by glatuske** [comment] 2023-01-14 06:44
Issued has been fixed for 3.0.x

**Closed** 2023-01-14 06:53 UTC
