### ISSUE TITLE
tycho-surefire-plugin:test does not resolve conditional bundles bound to non-primary environment

### ISSUE THREAD

**Issue by kwin** [eclipse-tycho/tycho#1900] opened 2022-12-22 08:03 UTC
The order of `environment` entries in https://tycho.eclipseprojects.io/doc/latest/target-platform-configuration/target-platform-configuration-mojo.html#environments seems to matter, as only the conditional bundles belonging to the *first* environment is properly resolved, e.g. when used in in a dependency given in https://tycho.eclipseprojects.io/doc/latest/tycho-surefire-plugin/test-mojo.html#dependencies.

Compare with the discussion at https://github.com/eclipse-m2e/m2e-core/discussions/1153

Expected behaviour:
The dependencies would be resolved from any(!) of the given environments matching conditional bundles.

**Comment by kwin** [comment] 2022-12-22 08:12
The issue seems to be in https://github.com/eclipse-tycho/tycho/blob/b12caef50b268837a0c23a7d9ce24655006427e4/tycho-core/src/main/java/org/eclipse/tycho/p2resolver/P2ResolverImpl.java#L153 which iterates over all environments. Unfortunately the first environment might already throw an exception (which is not caught), therefore the subsequent environment are not called.

**Comment by kwin** [comment] 2022-12-22 10:54
I provided a failing IT in https://github.com/eclipse-tycho/tycho/pull/1901 (only for Mac OS for now)

**Comment by laeubi** [comment] 2022-12-22 11:10
I think this is correct, i can't see that m2e is actually a "conditional bundle" that is one that defines a  eclipse-platform-filter.

**Comment by kwin** [comment] 2022-12-22 16:07
I don't get what is considered correct here. @laeubi Would you mind elaborating a bit? The bundle with filters in the example is not an m2e bundle but an Eclipse JDT one.

**Comment by laeubi** [comment] 2022-12-22 18:00
It is correct that the resolution fails. You example bundle does not define a platform-filter thus it is not platform dependent and need to resolve on all declared environments.

**Comment by kwin** [comment] 2022-12-22 18:19
How is this supposed to work with `eclipse-test-bundle` which are Bundle Fragments? I don't think that they are allowed to add a platform filter. In any case the error message is really poor and should explicitly state that in fact the bundle can only be resolved for one environment and not for others.

**Comment by laeubi** [comment] 2022-12-22 18:24
It is not a requirement that a `plugin-test` is a fragment, there is no such thing as "test fragments" anywhere in the spec.

> Also I don't think it is reasonable that all extra dependencies of a bundle need to have the same platform filter.

Extra requirements are nothing special, they are just there as a way to add items that are not directly required but the same rules apply to them.

**Comment by kwin** [comment] 2022-12-22 18:29
Do you agree that the situation with bundles having filters together with `tycho-surefire-plugin` needs to be improved? The only workarounds I know of and proposed by you in https://github.com/eclipse-m2e/m2e-core/discussions/1153 are

1. no environments at all, leading to warning durings build or 
2. profiles for each supported environment (3 tuple with each having 2 or more values, leading easily to a dozen different profiles). 

Both of them are nasty, so please propose a different way how use cases like this could be more easily supported.

**Comment by laeubi** [comment] 2022-12-22 18:44
> Do you agree that the situation with bundles having filters together with tycho-surefire-plugin needs to be improved? 

The provided example has no filter at all, if it would have one then it would not be resolving other targets at all. If you add an extra requirement it needs to resolve for all platform or your bundle/fragment need to define a filter itself, or you need to use a profile.

For the m2e case, I think there is a completely different problem, the project already resolved (as expected) without a problem, but `tycho-surefire-plugin` seem to select the windows environment to install the test-runtime (**what is wrong**) and therefore the install fails (**what is correct**) because obviously the platform dependent bundle can't be installed.

**Comment by kwin** [comment] 2022-12-22 18:52
> For the m2e case, I think there is a completely different problem

The provided IT fails with exactly the same error message as the m2e one and I tried my best to extract it from the real life m2e one. I don't know what makes you think that the IT exposes a different issue.

**Comment by laeubi** [comment] 2022-12-22 19:03
> > For the m2e case, I think there is a completely different problem
> 
> The provided IT fails with exactly the same error message as the m2e one and I tried my best to extract it from the real life m2e one. I don't know what makes you think that the IT exposes a different issue.

The IT is not different, but the problem is different than described here. The problem is not that Tycho can't resolve bundles in a conditional way (that already happens and works), also Tycho can skip environments that do not match the bundles platform filter (what do not apply here because the IT do not include such a bundle), the problem is that the **runtime install** is performed with a wrong environment (not matching the host!) and even though these two using the same codes and produce similar error messages they are different. If Tycho would not be able to resolve the project, the it won't run up to the integration-test phase (what it obviously does!).

**Comment by laeubi** [comment] 2022-12-24 08:32
I have now enhanced the `tycho-surefire-plugin` that it first tries to match any of the declared target-environments to  your build environment. If there is a match then the resolve uses the build environment to resolve the items for the test-runtime, otherwise one gets a warning that tests might not work as expected.

**Closed by laeubi** 2022-12-24 08:32 UTC

**Comment by kwin** [comment] 2022-12-24 11:49
Thanks, will try in the next days.
