### ISSUE TITLE
Tycho does not work with mvnd

### ISSUE THREAD

**Issue by gnodet** [eclipse-tycho/tycho#266] opened 2021-09-14 15:06 UTC
See https://github.com/mvndaemon/mvnd/issues/477

When building https://github.com/eclipse/eclipse.jdt.ls with `mvnd`, the tycho plugin fails the second time with the exception below.
This happens because mvnd caches the plugin realms, in this particular case, the tycho classloader is cached and reused across builds.  This cause the underlying equinox framework instance to be reused without being shutdown.

Not sure what's the best way to solve the problem: either having the tycho extension explicitely shut down the equinox framework when the build is finished or have only the P2 services being shutdown (no idea how atm)...

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:2.3.0:assemble-repository (default-assemble-repository) on project org.eclipse.jdt.ls.product: Could not assemble p2 repository: Mirroring failed: No repository found at file:/Users/gnodet/tmp/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:2.3.0:assemble-repository (default-assemble-repository) on project org.eclipse.jdt.ls.product: Could not assemble p2 repository
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:808)
	at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:242)
	at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:220)
	at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:573)
	at org.mvndaemon.mvnd.daemon.Server.client(Server.java:262)
	at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:230)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not assemble p2 repository
	at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute(AssembleRepositoryMojo.java:174)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 16 common frames omitted
Caused by: org.eclipse.tycho.p2.tools.FacadeException: Mirroring failed: No repository found at file:/Users/gnodet/tmp/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/.
	at org.eclipse.tycho.p2.tools.mirroring.MirrorApplicationServiceImpl.mirrorReactor(MirrorApplicationServiceImpl.java:176)
	at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute(AssembleRepositoryMojo.java:171)
	... 18 common frames omitted
Caused by: org.eclipse.equinox.p2.core.ProvisionException: No repository found at file:/Users/gnodet/tmp/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:396)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:700)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository(ArtifactRepositoryManager.java:131)
	at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.addRepository(AbstractApplication.java:156)
	at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.initializeRepos(AbstractApplication.java:124)
	at org.eclipse.equinox.p2.internal.repository.tools.MirrorApplication.run(MirrorApplication.java:199)
	at org.eclipse.tycho.p2.tools.mirroring.MirrorApplicationServiceImpl.mirrorReactor(MirrorApplicationServiceImpl.java:172)
	... 19 common frames omitted
```

**Comment by mickaelistria** [comment] 2021-09-14 17:00
> either having the tycho extension explicitely shut down the equinox framework when the build is finished or have only the P2 services being shutdown

The former is probably the simpler. It "only" requires to add to DefaultEquinoxEmbedder a "stop" method to stop Equinox and then find a way to call this method (directly or not) from TychoMavenLifecycleParticipant.

**Comment by gnodet** [comment] 2021-09-14 18:15
> > either having the tycho extension explicitely shut down the equinox framework when the build is finished or have only the P2 services being shutdown
> 
> The former is probably the simpler. It "only" requires to add to DefaultEquinoxEmbedder a "stop" method to stop Equinox and then find a way to call this method (directly or not) from TychoMavenLifecycleParticipant.

The `TychoMavenLifecycleParticipant ` can override the`afterSessionEnd` method and call the `stop` method in it, it should do the trick.

**Comment by gnodet** [comment] 2021-09-14 18:35
I've created https://github.com/eclipse/tycho/pull/267, unfortunately, this does not seem sufficient to solve the initial problem.  I end up with the following exception:
```
[ERROR] Internal error: java.lang.ClassCastException: class org.eclipse.equinox.internal.p2.metadata.InstallableUnit cannot be cast to class org.eclipse.equinox.p2.metadata.IInstallableUnit (org.eclipse.equinox.internal.p2.metadata.InstallableUnit is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @437554c1; org.eclipse.equinox.p2.metadata.IInstallableUnit is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @103f7ce6) -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ClassCastException
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:120)
	at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:808)
	at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:242)
	at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:220)
	at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:573)
	at org.mvndaemon.mvnd.daemon.Server.client(Server.java:262)
	at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:230)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.resolveProjects(TychoMavenLifecycleParticipant.java:162)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:106)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:264)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	... 7 common frames omitted
Caused by: java.lang.ClassCastException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$2(TychoMavenLifecycleParticipant.java:159)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassCastException: class org.eclipse.equinox.internal.p2.metadata.InstallableUnit cannot be cast to class org.eclipse.equinox.p2.metadata.IInstallableUnit (org.eclipse.equinox.internal.p2.metadata.InstallableUnit is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @437554c1; org.eclipse.equinox.p2.metadata.IInstallableUnit is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @103f7ce6)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.getPreliminaryReactorProjectUIs(TargetPlatformFactoryImpl.java:362)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:178)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:127)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1)
	at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:86)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:226)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:124)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$0(TychoMavenLifecycleParticipant.java:145)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SpinedBuffer.forEach(SpinedBuffer.java:250)
	at java.base/java.util.stream.Nodes$SpinedNodeBuilder.forEach(Nodes.java:1270)
	at java.base/java.util.stream.Nodes$InternalNodeSpliterator$OfRef.forEachRemaining(Nodes.java:1105)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	... 5 common frames omitted
```

**Comment by mickaelistria** [comment] 2021-09-14 21:18
The test did pass successfully and don't show this error. What are the steps to reproduce?

**Comment by gnodet** [comment] 2021-09-15 04:28
Here are the steps to reproduce the problem:
```
# build patched tycho
git clone https://github.com/gnodet/tycho
cd tycho
git checkout i266
mvn install -DskipTests
cd ..
# build patched eclipse.jdt.ls
git clone https://github.com/gnodet/eclipse.jdt.ls
cd eclipse.jdt.ls
mvnd install -DskipTests
mvnd install -DskipTests
```

**Comment by laeubi** [comment] 2021-09-15 05:05
>  This cause the underlying equinox framework instance to be reused without being shutdown.

I don't see a reason why this should not be desirable, reading what mvnd tries to accomplish it sounds reasonable to reuse the already started OSGi framework, this will actually improve startup-times as well. So the error you see now and the error before might be related and more shows that there is a classloader leak/refresh that is undesired if the following is true

>  mvnd caches the plugin realms

**Comment by gnodet** [comment] 2021-09-15 05:58
> > This cause the underlying equinox framework instance to be reused without being shutdown.
> 
> I don't see a reason why this should not be desirable, reading what mvnd tries to accomplish it sounds reasonable to reuse the already started OSGi framework, this will actually improve startup-times as well. So the error you see now and the error before might be related and more shows that there is a classloader leak/refresh that is undesired if the following is true.

That's right, but I don't think the code is prepared to cope with an already started framework at the moment, that's actually the first exception `org.eclipse.equinox.p2.core.ProvisionException: No repository found at file:/Users/gnodet/tmp/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/.`.  I don't know P2 much, so not sure why this happens...
The steps to reproduce the original issue are nearly the same:
```
git clone https://github.com/eclipse/eclipse.jdt.ls
cd eclipse.jdt.ls
mvnd install -DskipTests
mvnd install -DskipTests -e
``` 

> 
> > mvnd caches the plugin realms

**Comment by laeubi** [comment] 2021-09-15 06:13
I don't think the exception is related to the already started framework (actually multiple frameworks can be started simultaneously without a problem) but that the `assemble-repository` step tries to initialize but the path seems to be wrecked (actually I would expect something like `org.eclipse.jdt.ls.product/target/repository` here. I think your best bet would be to fire up a debugger and see what variables get different content in the second run to decide if this is an issue of mvnd or tycho.

**Comment by gnodet** [comment] 2021-09-15 06:36
> I don't think the exception is related to the already started framework (actually multiple frameworks can be started simultaneously without a problem) 

Well, that may be true in some cases, but not when using the `EclipseStarter`. This class supports a single framework stored in a static field.  Also, the `EclipseStarter` relies on setting system properties, so I really doubt it has been designed to support multiple concurrent frameworks. That may be related to the comment https://github.com/eclipse/tycho/blob/54c4a38aac5b4e94dca301538911cc7a43d347fe/sisu-equinox/sisu-equinox-embedder/src/main/java/org/eclipse/sisu/equinox/embedder/internal/DefaultEquinoxEmbedder.java#L168

> but that the `assemble-repository` step tries to initialize but the path seems to be wrecked (actually I would expect something like `org.eclipse.jdt.ls.product/target/repository` here.

This comes directly from https://github.com/eclipse/tycho/blob/1fbae13859a9e5456c24abccc0d9b3e0765efe0e/tycho-p2/tycho-p2-facade/src/main/java/org/eclipse/tycho/p2/facade/RepositoryReferenceTool.java#L90 and also https://github.com/eclipse/tycho/blob/1fbae13859a9e5456c24abccc0d9b3e0765efe0e/tycho-p2/tycho-p2-facade/src/main/java/org/eclipse/tycho/p2/facade/RepositoryReferenceTool.java#L142 (it's actually twice in the list).

>  I think your best bet would be to fire up a debugger and see what variables get different content in the second run to decide if this is an issue of mvnd or tycho.

Yes, that's what I did.  The input parameters are correct and are the same on both run.  But the second run fails with the exception. The difference is that in the second run, P2 is already initialised with the repositories.  Hence my initial suggestion to shutdown the framework.  It's the first time I look at tycho / p2, so I may certainly miss some context...

**Comment by laeubi** [comment] 2021-09-15 06:50
Can you put a breakpoint at AbstractRepositoryManager.loadRepository and check *why* it fails, the error is a bit vague what is the cause could be a missing file, a class load failure, ....

> Well, that may be true in some cases

That's how OSGi is defined, if Equinox do not work that way it won't be a valid framework implementation :-)

>  but not when using the `EclipseStarter`

That could be an issue, Eclipse often do/require dirty things ;-)
I still think it might be another issue (and your fix also indicates that there is another root cause beside the already started framework.

**Comment by gnodet** [comment] 2021-09-15 07:58
> Can you put a breakpoint at AbstractRepositoryManager.loadRepository and check _why_ it fails, the error is a bit vague what is the cause could be a missing file, a class load failure, ....
> 
> > Well, that may be true in some cases
> 
> That's how OSGi is defined, if Equinox do not work that way it won't be a valid framework implementation :-)

Yes, I've been working on OSGi for quite a long time, so I have a good understanding of how OSGi is defined :-)

> 
> > but not when using the `EclipseStarter`
> 
> That could be an issue, Eclipse often do/require dirty things ;-)

This is quite clear in this very case.  But as the comment says, switching to the real launcher should clean things a bit...

> I still think it might be another issue (and your fix also indicates that there is another root cause beside the already started framework.

I think the actual problem is the reuse of the P2 services.  If a build is meant to be reproductible, it has to start from a clean state, and having repositories still registered from previous builds looks really bad to me.  So while, I agree there should be no need to shutdown the framework, reusing the services when they are not stateless seems wrong to me.

I can try to investigate the initial cause, but it's quite hard given I don't have the exact source code in use : I'm not sure which exact bundles are loaded for P2 as they are not even maven dependencies.

Here's the status of the `AbstractRepositoryManager` at the failure point:
<img width="1079" alt="Screenshot 2021-09-15 at 09 53 24" src="https://user-images.githubusercontent.com/84022/133393473-cb11d6ae-c7f6-450a-a636-d4156c942b94.png">
and the local variables:
<img width="997" alt="Screenshot 2021-09-15 at 09 57 45" src="https://user-images.githubusercontent.com/84022/133393927-a8c3dbf3-f277-49dc-b519-1955df8a0979.png">

**Comment by gnodet** [comment] 2021-09-15 08:06
I just found something that could be part of the problem:
  https://github.com/eclipse/tycho/blob/30b797404f00fe248666d09f3ddae47d5a560307/tycho-bundles/org.eclipse.tycho.p2.tools.impl/src/main/java/org/eclipse/tycho/p2/tools/mirroring/MirrorApplication.java#L50
This forbids repositories that have been added to be removed (hence leave the managers in a clean state).
I'll try removing this line...

**Comment by gnodet** [comment] 2021-09-15 14:35
I may have found something: on the second run, the `/Users/gnodet/tmp/tmp2/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/p2artifacts.xml` has been deleted.
That's why the call to `AbstractRepositoryManager.loadRepository` fails with an exception.

**Comment by gnodet** [comment] 2021-09-15 19:48
It seems one of the problem comes from the fact that there are 2 instances of `DefaultAgentProvider` in memory, one created by `org.eclipse.equinox.internal.p2.core.Activator#registerAgent (188)` and the second one at `org.eclipse.tycho.p2.maven.repository.Activator#start (34)`.
This means that there are instances of the `ArtifactRepositoryManager` service registered in the framework.
One of them is correctly cleaned up with the above `finalizeRepositories()` method, but the other is not.
The fact that the repositories are still registered means that the existence of the actual file won't be checked and I think that's why if fails : I think the manager that is not cleaned is the one responsible for creating the repository `p2artifacts.xml` which is later supposed to simply exists (and fail with the initial exception).

**Comment by gnodet** [comment] 2021-09-16 13:56
This goes really beyond my area of expertise as I don't know the expected behaviours, so I'll leave it up to the expertise of the tycho committers.

Basically, the problem comes from the fact that the various `AbstractRepositoryManager` instances are not all cleaned up.  What seems to make things difficult is that some instances are retained through the `ProvisioningAgent` instances and some of them are kept in static singletons in activators.
I think this can be solved in _tycho_ only, but there's a need for a way to clean things when the maven session is ended.  Another possible way would be to fix the _p2_ code that load the repositories so that the actual existence of the file is verified before returning the repo in memory.

**Comment by laeubi** [comment] 2021-09-17 04:03
Thanks for all the infos and analysis. Have you tried calling mvn without the clean goal? Maybe this could serve as a workaround. Beside that I fear currently no one uses tycho with mvnd, so maybe you can just try to improve here in small steps (e.g. replace/release the static singletons?) like you already did with your PR to shut down the framework on session end.

On the other hand, I think it would be good if the mvnd project would go ahaed to define or extend something similar to the maven incremental build extension that allows compatible plugins to be aware of it, because this would allow tycho to really benefit from not being shut down. A large portion of the time for example is used to collect dependencies and this step could be omitted as long as the manifest not changes, the OSGI framework do not need to be shut down and the target platform could be keept as well.

**Comment by gnodet** [comment] 2021-09-17 11:13
> Thanks for all the infos and analysis. Have you tried calling mvn without the clean goal? Maybe this could serve as a workaround. 

I don't call the clean goal explicitly. It seems the project's pom is doing it. (and note I'm the author of `mvnd`, not the failing projects, so I have no idea why it's set up that way...)

> Beside that I fear currently no one uses tycho with mvnd, so maybe you can just try to improve here in small steps (e.g. replace/release the static singletons?) like you already did with your PR to shut down the framework on session end.

I've fixed the PR so that equinox is currently shutdown correctly which seems to do the trick.  The previous version was wrong because is was using the `PlexuContainer#dispose()` method which only works once.

> On the other hand, I think it would be good if the mvnd project would go ahaed to define or extend something similar to the maven incremental build extension that allows compatible plugins to be aware of it, because this would allow tycho to really benefit from not being shut down. A large portion of the time for example is used to collect dependencies and this step could be omitted as long as the manifest not changes, the OSGI framework do not need to be shut down and the target platform could be keept as well.

The lifecycle of some beans is a bit tricky between maven components which are usually disposed in a _normal_ build, but not in _mvnd_.  Fwiw, if collecting the dependencies means downloading them, you should set up a cache (maybe that's already done, as I said, the clean goal is part of the build and I haven't tried to remove it).

For now, I've provided a workaround in mvnd and fixed tycho, I think I've done my part of the job :-). I'll let the tycho team improve things if they want !

**Comment by laeubi** [comment] 2021-09-17 11:23
> I think I've done my part of the job :-)

Sure :-) Anyways contributions are always welcome.

>  Fwiw, if collecting the dependencies means downloading them

Download is cached (but some metadata is checked on each build) but for example if a project uses a target platform with planner mode, a configuration is calculated that full fills all declared dependencies. This process can take from seconds to minutes, depending on the size of the target. The next is, that for each bundle all requirements are collected and resolved and used to build the build-path. As these generally is fast (a few seconds) it could take a while as times are accumulate (tycho supports parallel resolves here so one could cut times down), these are definitely things that could be reused, e.g. if one want to recompile and only the source-code has changed (but not the requirements).

These data is currently cached in the MavenProject, is this data retained or will tycho get a new MavenProject instance for each run? Would the session (or any other place) be suitable to retain data between calls of `mvnd`?

**Comment by gnodet** [comment] 2021-09-17 11:52
> > I think I've done my part of the job :-)
> 
> Sure :-) Anyways contributions are always welcome.
> 
> > Fwiw, if collecting the dependencies means downloading them
> 
> Download is cached (but some metadata is checked on each build) but for example if a project uses a target platform with planner mode, a configuration is calculated that full fills all declared dependencies. This process can take from seconds to minutes, depending on the size of the target. The next is, that for each bundle all requirements are collected and resolved and used to build the build-path. As these generally is fast (a few seconds) it could take a while as times are accumulate (tycho supports parallel resolves here so one could cut times down), these are definitely things that could be reused, e.g. if one want to recompile and only the source-code has changed (but not the requirements).
> 
> These data is currently cached in the MavenProject, is this data retained or will tycho get a new MavenProject instance for each run? Would the session (or any other place) be suitable to retain data between calls of `mvnd`?

In the case of _tycho_ which is a maven extensions, the plexus container itself is reused, so any data kept inside a plexus bean can outlive the maven session.  This is the case for example of the `DefaultEquinoxEmbedder` which is annotated with the `@Component` plexus annotation.  The maven session is only for a given build.  The `MavenProject` is also recreated in _mvnd_, only the underlying maven `Model` is cached but you can't store anything in it.

Imho, to cache the results, I'd rather save the input requirements and output list of bundles to a file on disk after the resolution has been done and before actually doing the resolution, check the existence of the file, verify the input and use the precomputed output if there's a match.  This would benefit a broader set of usage.

**Comment by laeubi** [comment] 2022-03-08 18:56
@gnodet does `mvnd` work with the maven cache build extension? Then probably the following could improve build times:
- https://github.com/eclipse/tycho/issues/587

By the way should we keep this open or do you think tycho does work now with `mvnd` (we release 2.7.0 a while back that should include your fix).

**Comment by laeubi** [comment] 2023-01-29 06:44
As the referenced issue is closed as fixed and no one cared enough to work on this I'll close this for now.

If there are still specific issues left, please open a new ticket with steps to reproduce or even provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue.

**Closed by laeubi** 2023-01-29 06:44 UTC
Labels: enhancement, help wanted
