### ISSUE TITLE
tycho-versions-plugin hangs with MultiThreadedBuilder in Tycho 3.0.3

### ISSUE THREAD

**Issue by hd42** [eclipse-tycho/tycho#2169] opened 2023-02-27 09:35 UTC
When I try to run `mvn -V -T1C org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=23.6.0.a20230227-01 -DgenerateBackupPoms=false -Dartifacts=base,codequality-config,faktorips-coverage,faktorips-schemas` with Tycho 3.0.3 or 3.0.2, the last log I see is
`[INFO] Using the MultiThreadedBuilder implementation with a thread count of 16`
And then, there is no further output until I abort it after half an hour.
When I run the same without -T1C, it completes in less than 2 minutes.

**Comment by laeubi** [comment] 2023-02-27 10:39
What maven version do you use? Make it a difference if it is Maven 3.8 or Maven 3.9? Can you try out the Tycho 3/4 snapshots?

**Comment by hd42** [comment] 2023-02-27 12:15
This is on Maven 3.8.7. 
Switching to Tycho 3.0.4-SNAPSHOT did not help. 
Tycho 4.0.0-SNAPSHOT seems to require more changes than just the version number, as it fails with multiple [ERROR] Cannot resolve project dependencies, so I'm not testing this any further at the moment
Maven 3.9.0 shows the same problem.

**Comment by laeubi** [comment] 2023-03-02 11:33
Just to make sure, does this has worked with Tycho 3 before?

**Comment by hd42** [comment] 2023-03-02 11:35
No, we used it single-threaded before.

**Comment by laeubi** [comment] 2023-03-02 14:46
This is caused by [MNG-7716](https://issues.apache.org/jira/browse/MNG-7716) I'll prepare a patch for maven that hopefully will make it in the upcoming Maven 3.8.8 ...

**Comment by laeubi** [comment] 2023-03-05 15:37
This is now merged and schould be fixed in the next maven release.

**Closed by laeubi** 2023-03-05 15:37 UTC
Labels: sponsored
