### ISSUE TITLE
PGP signing mojo re-adds new signature properties for already signed artifacts

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-tycho/tycho#1466] opened 2022-10-04 13:29 UTC
If you're including in your p2 repo an artifact that already has some PGP signature (eg slf4j-api from Platform I-Build), and call the sign-p2-artifacts goal on it, then some new properties with the new signature and new key are added, leading to duplicated properties.
The mojo should provide a way to handle that case of already PGP-signed bundles:
* skip (keep original signature only)
* overwrite
* merge

**Comment by merks** [comment] 2022-11-14 13:09
Yes, I can confirm that this happens.   I've worked around various shortcomings and problems in the aggregator:

https://github.com/eclipse-cbi/p2repo-aggregator/issues/12

Here I add a fingerprint of the signing certificate to the artifact metadata, if there is one, and I record the original PGP signature/key:

https://github.com/eclipse-cbi/p2repo-aggregator/blob/ec3412a980ab15c3041e6b2792b3b82c04fa9dc9/plugins/org.eclipse.cbi.p2repo.aggregator.engine/src/org/eclipse/cbi/p2repo/aggregator/engine/MirrorGenerator.java#L446-L492

Then, after Tycho PGP signs all bundles and features, even ones that are jar-signed, I post process the metadata.  That let's me implement what you describe above:

https://github.com/eclipse-cbi/p2repo-aggregator/blob/ec3412a980ab15c3041e6b2792b3b82c04fa9dc9/plugins/org.eclipse.cbi.p2repo.aggregator.engine/src/org/eclipse/cbi/p2repo/aggregator/engine/SignatureCleaner.java#L71-L73

Some of this might be reusable (copy it and improve it):

https://github.com/eclipse-cbi/p2repo-aggregator/blob/ec3412a980ab15c3041e6b2792b3b82c04fa9dc9/plugins/org.eclipse.cbi.p2repo.aggregator.engine/src/org/eclipse/cbi/p2repo/aggregator/engine/SignatureCleaner.java#L170-L297

The processing here also lets me "reject" certain certificates, ones Tycho doesn't recognize as being treated as unsigned (even when running with a 17.0.5+8 JRE where jarsigner should detect that) and then I retain the new PGP signatures for those artifacts.

But my biggest problem now, one that I cannot work around, is that PGP signed features don't validate. 

- https://download.eclipse.org/staging/2022-12/buildInfo/archive/download.eclipse.org/staging/2022-12/index/org.eclipse.uml2.feature.jar_5.5.2.v20210228-1829.html
- https://download.eclipse.org/staging/2022-12/features/org.eclipse.uml2_5.5.2.v20210228-1829.jar

Obviously I need to open issues for some of these issues, but I'm been swamped...

**Comment by merks** [comment] 2022-11-19 16:35
@laeubi  @mickaelistria 

I'd like to start implementing support for this.  Unless I've overlooked something though, I see no test cases related to org.eclipse.tycho.gpg.SignRepositoryArtifactsMojo.   Or did I overlook something?

I have been able to test it locally by creating a key in my ~/.gnupg folder and using that, but I don't know if such a thing can be made portable across OSes for an actual test case that's committed...

**Comment by laeubi** [comment] 2022-11-19 16:40
I think we recently have had a similar case where it was considered to complex to have a full PGP setup for testing ([even though there are some ways](https://github.com/sniggle/simple-pgp/blob/master/simple-pgp-java/src/main/java/me/sniggle/pgp/crypt/PGPKeyPairGenerator.java)) because that uses the native PGP tooling.

So this is mostly tested manually and tried to find issues by code reviews.

**Comment by merks** [comment] 2022-11-24 11:52
@laeubi This can be closed as completed now.

**Closed** 2022-11-24 11:52 UTC
