### ISSUE TITLE
537320 : Regression on support for "external" bundle-classpath

### ISSUE THREAD

**Issue by lazyleo13** [eclipse-tycho/tycho#62] opened 2021-04-12 10:12 UTC
https://bugs.eclipse.org/bugs/show_bug.cgi?id=537320

We are migrating the project from java8 to java11. Earlier we were using tycho version 1.0.0 and could build the project with an entry like this under 

Bundle-ClassPath : external:$user.dir

On switching to jdk11, we have to upgrade tycho version to 1.3.0 since Tycho 1.0.0 does not support jdk11. But with new version the build is getting failed with the error message : "Fatal error compiling: Illegal char <:> at index 94"

We are using eclipse 4.16 and I believe the issue is still not resolved in latest release of eclipse.

Note: I have tried working with 2.4.0-SNAPSHOT , but the error still occurs with same Caused by: org.codehaus.plexus.compiler.CompilerException: Illegal char <:> at index 93: D:\Git\com.test.build\external:$user.dir$\test\lib\jdmktk.jar

**Comment by laeubi** [comment] 2021-04-12 10:22
You should really upgrade to tycho 2.3.0, previous versions are no longer officially supported.

Can you give a reference on PDE or JDT that describes the semantic and support of `Bundle-ClassPath : external:$user.dir` I have never heard about it and you are most probably the only consumer of that feature given that it is broken for such a long time.
Can you describe the usecase? Tycho might support better alternatives maybe?

**Comment by mickaelistria** [comment] 2021-04-12 10:30
@laeubi see https://bugs.eclipse.org/bugs/show_bug.cgi?id=537320#c13 for details of where `external:` is used by Equinox.

**Comment by laeubi** [comment] 2021-04-12 10:45
I have checked the code and it seems this is intended for Bundle-Native code indeed that it works for Bundle-ClassPath seems not be covered by any test, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=238675 that mentions this feature...

**Comment by laeubi** [comment] 2021-04-12 10:53
@lazyleo13 can you provide a Pull Reqeust with a failing test-case in https://github.com/eclipse/tycho/tree/master/tycho-its that shows the problem?

**Comment by laeubi** [comment] 2021-04-12 17:14
it seems org.eclipse.osgi.internal.framework.EquinoxConfiguration.ConfigValues is responsible for parsing this, we might can copy the code here, but I still get the impression that this is solely for native code as the real entry where this is used resides in org.eclipse.osgi.storage.NativeCodeFinder

**Comment by Kellindil** [comment] 2021-07-26 13:10
Please note that a failing test case is available on the original bug : https://bugs.eclipse.org/bugs/show_bug.cgi?id=537320

**Comment by Kellindil** [comment] 2021-07-27 13:53
This actually seems to be a regression in the jdt instead of tycho.

Specifically, org.eclipse.jdt.internal.compiler.apt.util.EclipseFileManager.setLocation(Location, Iterable<? extends File>) has changed in such a way that it tries to parse the classpath entries as java.nio.file.Path... which cannot work with "external:" references. This regression was introduced by https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/commit/?id=c798229d351d6daa2232cff6c15750336659223e .

I am not sure where to go from there. It seems like we would have to actually parse the classpath entry before we even pass it to org.eclipse.jdt.internal.compiler.batch.Main (from org.eclipse.tycho.compiler.jdt.JDTCompiler.compileInProcess(String[], CustomCompilerConfiguration)) in order to either a) send a resolved entry or b) not send it at all ?

**Comment by laeubi** [comment] 2021-07-27 13:54
@Kellindil if its a problem with JDT it should be resolved/reported there. Once it is fixed and released, we can integrate this in tycho.

**Comment by Kellindil** [comment] 2021-07-27 14:23
I have raised https://bugs.eclipse.org/bugs/show_bug.cgi?id=575072 to track this against the JDT

**Comment by Kellindil** [comment] 2021-07-30 10:06
For anyone else stumbling on this and until bug 575072 is fixed by the JDT team. If what you are building is a product, you can use the following to workaround this issue:

* remove the "external:" prefix from the MANIFEST.MF classpath entries (so that the build through tycho can finish)
* add the "Eclipse-BundleShape: dir" entry to the same MANIFEST.MF (which means in the product generated by your build, the plugin will be there in the form of a plain folder instead of a jar file in the "plugins" folder)
* use the maven-replacer-plugin to manually prefix all classpath entries with "external:" in that MANIFEST in the generated product (these classpath entries will be read and resolved when first starting the product, so as long as the external prefix is there, eclipse will properly resolve against an external path). Make sure it is called in the "package" phase.

Here is how it looks like in my build for reference:
`
<plugin>
        <groupId>com.google.code.maven-replacer-plugin</groupId>
        <artifactId>replacer</artifactId>
        <version>1.5.3</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>replace</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <includes>
            <include>${project.build.directory}/products/${product-bundle-id}/linux/gtk/x86_64/plugins/my.plugin.id_${qualifiedVersion}/META-INF/MANIFEST.MF</include>
            <include>${project.build.directory}/products/${product-bundle-id}/win32/win32/x86_64/plugins/my.plugin.id_${qualifiedVersion}/META-INF/MANIFEST.MF</include>
          </includes>
          <replacements>
            <replacement>
              
              <token>(\$\s*?v\s*?a\s*?r)</token>
              <value>external:$1</value>
            </replacement>
          </replacements>
        </configuration>
      </plugin>
`

**Comment by laeubi** [comment] 2022-10-19 05:09
As no action for more than a year I'll close this for now as it seems JDT still don't support this. But feel free to report back here if there is still something to do and we can make progress e.g. by provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue and JDT has fixed the problem.

**Closed by laeubi** 2022-10-19 05:09 UTC
